services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/cache/nginx
  backend:
    build:
      context: ./backend
      target: final
    environment:
      - GoogleBooksApiKey=${GOOGLEBOOKSAPIKEY}
    ports:
      - 5088:8080
    depends_on:
       db:
         condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    # secrets:
    #   - db-password
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=books
      - POSTGRES_PASSWORD=Abc.123
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
# secrets:
#   db-password:
#     file: db/password.txt

